# Based on https://www.tomray.dev/nestjs-docker-compose-postgres
version: '3.8'
services:
  metadata-gpt-nestjs:
    container_name: metadata-gpt-nestjs
    depends_on:
      - metadata-gpt-redis
      - metadata-gpt-postgres
    build:
      context: .
      # Only will build local stage from our dockerfile
      target: local
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    # Run a command against the local stage of the image
    command: pnpm start:debug
    ports:
      - ${PORT}:${PORT}
      - 9229:9229

  metadata-gpt-postgres:
    container_name: metadata-gpt-postgres
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${LOCAL_POSTGRES_PORT}:5432'
    volumes:
      - metadata-gpt-postgres:/var/lib/postgresql/data

  metadata-gpt-redis:
    container_name: metadata-gpt-redis
    image: redis:7.2.1-alpine3.18
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - metadata-gpt-redis:/data

  metadata-gpt-opensearch:
    image: opensearchproject/opensearch:2.6.0
    container_name: metadata-gpt-opensearch
    environment:
      - cluster.name=metadata-gpt-opensearch
      - node.name=metadata-gpt-opensearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - metadata_gpt_opensearch_data:/usr/share/metadata_gpt_opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
  metadata-gpt-opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.6.0 # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
    container_name: metadata-gpt-opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["http://metadata-gpt-opensearch:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true" # disables security dashboards plugin in OpenSearch Dashboards

volumes:
  metadata-gpt-postgres:
  metadata-gpt-redis:
    driver: local
  metadata_gpt_opensearch_data:
