# Based on https://www.tomray.dev/nestjs-docker-compose-postgres
version: '3.8'
services:
  chat-stack-nestjs:
    container_name: chat-stack-nestjs
    depends_on:
      - chat-stack-redis
      - chat-stack-postgres
      - chat-stack-opensearch
      - chat-stack-opensearch-dashboards
    build:
      no_cache: false # turn this on if you want to build without cache
      context: .
      # Only will build local stage from our dockerfile
      target: local
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    # Run a command against the local stage of the image
    command: pnpm run start:debug
    ports:
      - ${PORT}:${PORT}
      - 9229:9229

  chat-stack-postgres:
    container_name: chat-stack-postgres
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${LOCAL_POSTGRES_PORT}:5432'
    volumes:
      - chat-stack-postgres:/var/lib/postgresql/data

  chat-stack-redis:
    container_name: chat-stack-redis
    image: redis:7.2.1-alpine3.18
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - chat-stack-redis:/data

  chat-stack-opensearch:
    image: opensearchproject/opensearch:2.6.0
    container_name: chat-stack-opensearch
    environment:
      - cluster.name=chat-stack-opensearch
      - node.name=chat-stack-opensearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - chat_stack_opensearch_data:/usr/share/chat_stack_opensearch/data
    ports:
      - 9200:9200
      - 9600:9600

  chat-stack-opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.6.0 # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
    container_name: chat-stack-opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["http://chat-stack-opensearch:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true" # disables security dashboards plugin in OpenSearch Dashboards

volumes:
  chat-stack-postgres:
  chat-stack-redis:
    driver: local
  chat_stack_opensearch_data:
